Sync changes from docker/docker-yt-dlp directory

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -4,6 +4,17 @@ executors:
   docker-build-buster:
     docker:
       - image: circleci/buildpack-deps:buster
+  docker-push-files-2-dockerhub:
+    docker:
+    - image: gofunky/readmyhub:1.2.2-envload
+    environment:
+      README_PATH: /data/<< parameters.file >>
+    parameters:
+      file:
+        default: README.md
+        description: Path to the README.md file
+        type: string
+    working_directory: /data
 
 jobs:
   build:
@@ -64,6 +75,32 @@ jobs:
 #      - run:
 #          name: Push Docker image to Quay.io
 #          command: make quay-push
+  upload-files:
+    description: Push the given README.md to the Docker Hub
+    executor:
+      name: docker-push-files-2-dockerhub
+      file: << parameters.file >>
+      name: default
+    parameters:
+      file:
+        default: README.md
+        description: Path to the README.md file
+        type: string
+      organization:
+        default: ""
+        description: |
+          Docker Hub organization or user name. Environment variables from envorbs are accepted. By default, the git organization is assumed.
+        type: string
+      repository:
+        default: ""
+        description: |
+          Docker Hub repository name. Environment variables from envorbs are accepted. By default, the git repository name is assumed.
+        type: string
+    steps:
+    - checkout
+    - upload-files:
+        organization: << parameters.organization >>
+        repository: << parameters.repository >>
 
 workflows:
   version: 2
@@ -79,6 +116,10 @@ workflows:
 #      - publish-quay:
 #          requires:
 #            - test
+      # Afegit per tal de pujar el readme.md (o qualsevol arxiu) a dockerhub
+      - upload-files:
+          requires:
+            - publish-dockerhub  
   nightly-build-deploy:
     triggers:
       - schedule:
@@ -95,6 +136,89 @@ workflows:
       - publish-dockerhub:
           requires:
             - test
+      # Afegit per tal de pujar el readme.md (o qualsevol arxiu) a dockerhub
+      - upload-files:
+          requires:
+            - publish-dockerhub  
 #      - publish-quay:
 #          requires:
 #            - test
+
+# Aixo es necesari per pujar el readme.md a dockerhub
+commands:
+  update:
+    parameters:
+      organization:
+        default: ""
+        description: |
+          Docker Hub organization or user name. Environment variables from envorbs are accepted. By default, the git organization is assumed.
+        type: string
+      repository:
+        default: ""
+        description: |
+          Docker Hub repository name. Environment variables from envorbs are accepted. By default, the git repository name is assumed.
+        type: string
+    steps:
+    - run:
+        command: |
+          if [ -z "$DOCKERHUB_USERNAME" ]; then
+            echo "ERROR: DOCKERHUB_USERNAME is not set!"
+            exit 127
+          fi
+        name: Check DOCKERHUB_USERNAME
+    - run:
+        command: |
+          if [ -z "$DOCKERHUB_PASSWORD" ]; then
+            echo "ERROR: DOCKERHUB_PASSWORD is not set!"
+            exit 127
+          fi
+        name: Check DOCKERHUB_PASSWORD
+    - when:
+        condition: << parameters.organization >>
+        steps:
+        - envorb/value:
+            value: << parameters.organization >>
+            variable: DOCKERHUB_ORG
+    - unless:
+        condition: << parameters.organization >>
+        steps:
+        - envorb/git_org:
+            variable: DOCKERHUB_ORG
+    - when:
+        condition: << parameters.repository >>
+        steps:
+        - envorb/value:
+            value: << parameters.repository >>
+            variable: DOCKERHUB_REPO
+    - unless:
+        condition: << parameters.repository >>
+        steps:
+        - envorb/git_name:
+            variable: DOCKERHUB_REPO
+    - run:
+        command: |
+          source /usr/local/bin/envload
+          export DOCKERHUB_USR=${DOCKERHUB_USERNAME}
+          export DOCKERHUB_PWD=${DOCKERHUB_PASSWORD}
+          node /app/index.js
+        name: Upload README
+
+description: Allows you to push README.md files to the Docker Hub.
+orbs:
+  envorb: gofunky/envorb@0.3.9
+readmyhub_params:
+  file:
+    default: README.md
+    description: Path to the README.md file
+    type: string
+readmyhub_update_params:
+  organization:
+    default: ""
+    description: |
+      Docker Hub organization or user name. Environment variables from envorbs are accepted. By default, the git organization is assumed.
+    type: string
+  repository:
+    default: ""
+    description: |
+      Docker Hub repository name. Environment variables from envorbs are accepted. By default, the git repository name is assumed.
+    type: string
